<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $countries = [
            [
                'name' => 'Indonesia',
                'code' => 'ID',
                'region' => 'Southeast Asia',
                'risk_score' => 25,
                'risk_level' => 'Low',
                'trade_index' => 88,
                'shipping_status' => 'Normal',
                'supply_status' => 'Normal',
                'latitude' => -6.200000,
                'longitude' => 106.816666,
                'gdp' => '$1.37 Trillion',
                'inflation' => 2.84,
                'population' => 277500000,
                'currency' => 'IDR',
            ],
            [
                'name' => 'China',
                'code' => 'CN',
                'region' => 'East Asia',
                'risk_score' => 47,
                'risk_level' => 'Medium',
                'trade_index' => 95,
                'shipping_status' => 'Delayed',
                'supply_status' => 'Limited',
                'latitude' => 39.9042,
                'longitude' => 116.4074,
                'gdp' => '$17.96 Trillion',
                'inflation' => 0.70,
                'population' => 1412000000,
                'currency' => 'CNY',
            ],
            [
                'name' => 'Germany',
                'code' => 'DE',
                'region' => 'Europe',
                'risk_score' => 22,
                'risk_level' => 'Low',
                'trade_index' => 91,
                'shipping_status' => 'Normal',
                'supply_status' => 'Normal',
                'latitude' => 52.5200,
                'longitude' => 13.4050,
                'gdp' => '$4.07 Trillion',
                'inflation' => 2.20,
                'population' => 84400000,
                'currency' => 'EUR',
            ],
            [
                'name' => 'Australia',
                'code' => 'AU',
                'region' => 'Oceania',
                'risk_score' => 19,
                'risk_level' => 'Low',
                'trade_index' => 89,
                'shipping_status' => 'Normal',
                'supply_status' => 'Normal',
                'latitude' => -35.2809,
                'longitude' => 149.1300,
                'gdp' => '$1.68 Trillion',
                'inflation' => 3.60,
                'population' => 26400000,
                'currency' => 'AUD',
            ],
            [
                'name' => 'United States',
                'code' => 'US',
                'region' => 'North America',
                'risk_score' => 55,
                'risk_level' => 'Medium',
                'trade_index' => 97,
                'shipping_status' => 'Delayed',
                'supply_status' => 'Normal',
                'latitude' => 38.9072,
                'longitude' => -77.0369,
                'gdp' => '$25.46 Trillion',
                'inflation' => 3.10,
                'population' => 333300000,
                'currency' => 'USD',
            ],
            [
                'name' => 'Japan',
                'code' => 'JP',
                'region' => 'East Asia',
                'risk_score' => 20,
                'risk_level' => 'Low',
                'trade_index' => 92,
                'shipping_status' => 'Normal',
                'supply_status' => 'Normal',
                'latitude' => 35.6762,
                'longitude' => 139.6503,
                'gdp' => '$4.23 Trillion',
                'inflation' => 2.50,
                'population' => 125100000,
                'currency' => 'JPY',
            ],
            [
                'name' => 'India',
                'code' => 'IN',
                'region' => 'South Asia',
                'risk_score' => 83,
                'risk_level' => 'High',
                'trade_index' => 74,
                'shipping_status' => 'Critical',
                'supply_status' => 'Disrupted',
                'latitude' => 28.6139,
                'longitude' => 77.2090,
                'gdp' => '$3.39 Trillion',
                'inflation' => 5.10,
                'population' => 1428000000,
                'currency' => 'INR',
            ],
            [
                'name' => 'Singapore',
                'code' => 'SG',
                'region' => 'Southeast Asia',
                'risk_score' => 12,
                'risk_level' => 'Low',
                'trade_index' => 99,
                'shipping_status' => 'Normal',
                'supply_status' => 'Normal',
                'latitude' => 1.3521,
                'longitude' => 103.8198,
                'gdp' => '$466.8 Billion',
                'inflation' => 2.70,
                'population' => 5640000,
                'currency' => 'SGD',
            ],
            [
                'name' => 'South Korea',
                'code' => 'KR',
                'region' => 'East Asia',
                'risk_score' => 35,
                'risk_level' => 'Low',
                'trade_index' => 90,
                'shipping_status' => 'Normal',
                'supply_status' => 'Normal',
                'latitude' => 37.5665,
                'longitude' => 126.9780,
                'gdp' => '$1.67 Trillion',
                'inflation' => 2.90,
                'population' => 51700000,
                'currency' => 'KRW',
            ],
            [
                'name' => 'Vietnam',
                'code' => 'VN',
                'region' => 'Southeast Asia',
                'risk_score' => 49,
                'risk_level' => 'Low',
                'trade_index' => 80,
                'shipping_status' => 'Delayed',
                'supply_status' => 'Limited',
                'latitude' => 21.0278,
                'longitude' => 105.8342,
                'gdp' => '$409 Billion',
                'inflation' => 3.25,
                'population' => 98800000,
                'currency' => 'VND',
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['code' => $country['code']], $country);
        }
    }
}