<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $countries = [

           [
    'name' => 'Indonesia',
    'code' => 'ID',
    'iso3' => 'IDN',
    'capital' => 'Jakarta',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'IDR',
    'population' => 278696200,
    'gdp' => 1371000000000,
    'latitude' => -6.2088,
    'longitude' => 106.8456,
    'risk_level' => 'Medium',
    'risk_score' => 65,
    'trade_index' => 82,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Malaysia',
    'code' => 'MY',
    'iso3' => 'MYS',
    'capital' => 'Kuala Lumpur',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'MYR',
    'population' => 34300000,
    'gdp' => 445000000000,
    'latitude' => 3.1390,
    'longitude' => 101.6869,
    'risk_level' => 'Low',
    'risk_score' => 32,
    'trade_index' => 87,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Singapore',
    'code' => 'SG',
    'iso3' => 'SGP',
    'capital' => 'Singapore',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'SGD',
    'population' => 5920000,
    'gdp' => 501000000000,
    'latitude' => 1.3521,
    'longitude' => 103.8198,
    'risk_level' => 'Low',
    'risk_score' => 25,
    'trade_index' => 96,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Thailand',
    'code' => 'TH',
    'iso3' => 'THA',
    'capital' => 'Bangkok',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'THB',
    'population' => 71800000,
    'gdp' => 543000000000,
    'latitude' => 13.7563,
    'longitude' => 100.5018,
    'risk_level' => 'Medium',
    'risk_score' => 48,
    'trade_index' => 81,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Vietnam',
    'code' => 'VN',
    'iso3' => 'VNM',
    'capital' => 'Hanoi',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'VND',
    'population' => 101000000,
    'gdp' => 433000000000,
    'latitude' => 21.0278,
    'longitude' => 105.8342,
    'risk_level' => 'Low',
    'risk_score' => 36,
    'trade_index' => 84,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Philippines',
    'code' => 'PH',
    'iso3' => 'PHL',
    'capital' => 'Manila',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'PHP',
    'population' => 117000000,
    'gdp' => 437000000000,
    'latitude' => 14.5995,
    'longitude' => 120.9842,
    'risk_level' => 'Medium',
    'risk_score' => 55,
    'trade_index' => 78,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'China',
    'code' => 'CN',
    'iso3' => 'CHN',
    'capital' => 'Beijing',
    'region' => 'Asia',
    'sub_region' => 'Eastern Asia',
    'currency' => 'CNY',
    'population' => 1410000000,
    'gdp' => 17960000000000,
    'latitude' => 39.9042,
    'longitude' => 116.4074,
    'risk_level' => 'Medium',
    'risk_score' => 60,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Japan',
    'code' => 'JP',
    'iso3' => 'JPN',
    'capital' => 'Tokyo',
    'region' => 'Asia',
    'sub_region' => 'Eastern Asia',
    'currency' => 'JPY',
    'population' => 123000000,
    'gdp' => 4210000000000,
    'latitude' => 35.6762,
    'longitude' => 139.6503,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 93,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'South Korea',
    'code' => 'KR',
    'iso3' => 'KOR',
    'capital' => 'Seoul',
    'region' => 'Asia',
    'sub_region' => 'Eastern Asia',
    'currency' => 'KRW',
    'population' => 51700000,
    'gdp' => 1710000000000,
    'latitude' => 37.5665,
    'longitude' => 126.9780,
    'risk_level' => 'Low',
    'risk_score' => 28,
    'trade_index' => 91,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'India',
    'code' => 'IN',
    'iso3' => 'IND',
    'capital' => 'New Delhi',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'INR',
    'population' => 1430000000,
    'gdp' => 3730000000000,
    'latitude' => 28.6139,
    'longitude' => 77.2090,
    'risk_level' => 'Medium',
    'risk_score' => 58,
    'trade_index' => 83,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],
[
    'name' => 'Pakistan',
    'code' => 'PK',
    'iso3' => 'PAK',
    'capital' => 'Islamabad',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'PKR',
    'population' => 241500000,
    'gdp' => 338000000000,
    'latitude' => 33.6844,
    'longitude' => 73.0479,
    'risk_level' => 'High',
    'risk_score' => 72,
    'trade_index' => 63,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Bangladesh',
    'code' => 'BD',
    'iso3' => 'BGD',
    'capital' => 'Dhaka',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'BDT',
    'population' => 173000000,
    'gdp' => 460000000000,
    'latitude' => 23.8103,
    'longitude' => 90.4125,
    'risk_level' => 'Medium',
    'risk_score' => 60,
    'trade_index' => 72,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Sri Lanka',
    'code' => 'LK',
    'iso3' => 'LKA',
    'capital' => 'Sri Jayawardenepura Kotte',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'LKR',
    'population' => 22000000,
    'gdp' => 84000000000,
    'latitude' => 6.9271,
    'longitude' => 79.8612,
    'risk_level' => 'Medium',
    'risk_score' => 57,
    'trade_index' => 65,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Nepal',
    'code' => 'NP',
    'iso3' => 'NPL',
    'capital' => 'Kathmandu',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'NPR',
    'population' => 30900000,
    'gdp' => 41000000000,
    'latitude' => 27.7172,
    'longitude' => 85.3240,
    'risk_level' => 'Medium',
    'risk_score' => 52,
    'trade_index' => 58,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Myanmar',
    'code' => 'MM',
    'iso3' => 'MMR',
    'capital' => 'Naypyidaw',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'MMK',
    'population' => 55000000,
    'gdp' => 65000000000,
    'latitude' => 19.7633,
    'longitude' => 96.0785,
    'risk_level' => 'High',
    'risk_score' => 82,
    'trade_index' => 44,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Laos',
    'code' => 'LA',
    'iso3' => 'LAO',
    'capital' => 'Vientiane',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'LAK',
    'population' => 7600000,
    'gdp' => 16000000000,
    'latitude' => 17.9757,
    'longitude' => 102.6331,
    'risk_level' => 'Low',
    'risk_score' => 38,
    'trade_index' => 54,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Cambodia',
    'code' => 'KH',
    'iso3' => 'KHM',
    'capital' => 'Phnom Penh',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'KHR',
    'population' => 17000000,
    'gdp' => 33000000000,
    'latitude' => 11.5564,
    'longitude' => 104.9282,
    'risk_level' => 'Medium',
    'risk_score' => 49,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Brunei',
    'code' => 'BN',
    'iso3' => 'BRN',
    'capital' => 'Bandar Seri Begawan',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'BND',
    'population' => 460000,
    'gdp' => 17000000000,
    'latitude' => 4.9031,
    'longitude' => 114.9398,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Timor-Leste',
    'code' => 'TL',
    'iso3' => 'TLS',
    'capital' => 'Dili',
    'region' => 'Asia',
    'sub_region' => 'South-Eastern Asia',
    'currency' => 'USD',
    'population' => 1400000,
    'gdp' => 2100000000,
    'latitude' => -8.5569,
    'longitude' => 125.5603,
    'risk_level' => 'Medium',
    'risk_score' => 55,
    'trade_index' => 46,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Mongolia',
    'code' => 'MN',
    'iso3' => 'MNG',
    'capital' => 'Ulaanbaatar',
    'region' => 'Asia',
    'sub_region' => 'Eastern Asia',
    'currency' => 'MNT',
    'population' => 3500000,
    'gdp' => 20000000000,
    'latitude' => 47.8864,
    'longitude' => 106.9057,
    'risk_level' => 'Low',
    'risk_score' => 35,
    'trade_index' => 57,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Saudi Arabia',
    'code' => 'SA',
    'iso3' => 'SAU',
    'capital' => 'Riyadh',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'SAR',
    'population' => 37100000,
    'gdp' => 1106000000000,
    'latitude' => 24.7136,
    'longitude' => 46.6753,
    'risk_level' => 'Low',
    'risk_score' => 30,
    'trade_index' => 90,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'United Arab Emirates',
    'code' => 'AE',
    'iso3' => 'ARE',
    'capital' => 'Abu Dhabi',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'AED',
    'population' => 10300000,
    'gdp' => 509000000000,
    'latitude' => 24.4539,
    'longitude' => 54.3773,
    'risk_level' => 'Low',
    'risk_score' => 22,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Qatar',
    'code' => 'QA',
    'iso3' => 'QAT',
    'capital' => 'Doha',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'QAR',
    'population' => 2700000,
    'gdp' => 235000000000,
    'latitude' => 25.2854,
    'longitude' => 51.5310,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 94,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Kuwait',
    'code' => 'KW',
    'iso3' => 'KWT',
    'capital' => 'Kuwait City',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'KWD',
    'population' => 4300000,
    'gdp' => 165000000000,
    'latitude' => 29.3759,
    'longitude' => 47.9774,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Bahrain',
    'code' => 'BH',
    'iso3' => 'BHR',
    'capital' => 'Manama',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'BHD',
    'population' => 1600000,
    'gdp' => 44000000000,
    'latitude' => 26.2235,
    'longitude' => 50.5876,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 86,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Oman',
    'code' => 'OM',
    'iso3' => 'OMN',
    'capital' => 'Muscat',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'OMR',
    'population' => 4700000,
    'gdp' => 109000000000,
    'latitude' => 23.5880,
    'longitude' => 58.3829,
    'risk_level' => 'Low',
    'risk_score' => 27,
    'trade_index' => 82,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Iran',
    'code' => 'IR',
    'iso3' => 'IRN',
    'capital' => 'Tehran',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'IRR',
    'population' => 90000000,
    'gdp' => 404000000000,
    'latitude' => 35.6892,
    'longitude' => 51.3890,
    'risk_level' => 'High',
    'risk_score' => 80,
    'trade_index' => 55,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Iraq',
    'code' => 'IQ',
    'iso3' => 'IRQ',
    'capital' => 'Baghdad',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'IQD',
    'population' => 46000000,
    'gdp' => 265000000000,
    'latitude' => 33.3152,
    'longitude' => 44.3661,
    'risk_level' => 'High',
    'risk_score' => 84,
    'trade_index' => 48,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Turkey',
    'code' => 'TR',
    'iso3' => 'TUR',
    'capital' => 'Ankara',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'TRY',
    'population' => 86000000,
    'gdp' => 1118000000000,
    'latitude' => 39.9334,
    'longitude' => 32.8597,
    'risk_level' => 'Medium',
    'risk_score' => 52,
    'trade_index' => 84,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Kazakhstan',
    'code' => 'KZ',
    'iso3' => 'KAZ',
    'capital' => 'Astana',
    'region' => 'Asia',
    'sub_region' => 'Central Asia',
    'currency' => 'KZT',
    'population' => 20300000,
    'gdp' => 288000000000,
    'latitude' => 51.1694,
    'longitude' => 71.4491,
    'risk_level' => 'Low',
    'risk_score' => 34,
    'trade_index' => 74,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Uzbekistan',
    'code' => 'UZ',
    'iso3' => 'UZB',
    'capital' => 'Tashkent',
    'region' => 'Asia',
    'sub_region' => 'Central Asia',
    'currency' => 'UZS',
    'population' => 36700000,
    'gdp' => 115000000000,
    'latitude' => 41.2995,
    'longitude' => 69.2401,
    'risk_level' => 'Medium',
    'risk_score' => 45,
    'trade_index' => 68,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Turkmenistan',
    'code' => 'TM',
    'iso3' => 'TKM',
    'capital' => 'Ashgabat',
    'region' => 'Asia',
    'sub_region' => 'Central Asia',
    'currency' => 'TMT',
    'population' => 6600000,
    'gdp' => 60000000000,
    'latitude' => 37.9601,
    'longitude' => 58.3261,
    'risk_level' => 'Medium',
    'risk_score' => 50,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Kyrgyzstan',
    'code' => 'KG',
    'iso3' => 'KGZ',
    'capital' => 'Bishkek',
    'region' => 'Asia',
    'sub_region' => 'Central Asia',
    'currency' => 'KGS',
    'population' => 7200000,
    'gdp' => 14000000000,
    'latitude' => 42.8746,
    'longitude' => 74.5698,
    'risk_level' => 'Medium',
    'risk_score' => 47,
    'trade_index' => 54,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Tajikistan',
    'code' => 'TJ',
    'iso3' => 'TJK',
    'capital' => 'Dushanbe',
    'region' => 'Asia',
    'sub_region' => 'Central Asia',
    'currency' => 'TJS',
    'population' => 10500000,
    'gdp' => 12000000000,
    'latitude' => 38.5598,
    'longitude' => 68.7870,
    'risk_level' => 'Medium',
    'risk_score' => 53,
    'trade_index' => 50,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Afghanistan',
    'code' => 'AF',
    'iso3' => 'AFG',
    'capital' => 'Kabul',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'AFN',
    'population' => 43000000,
    'gdp' => 17000000000,
    'latitude' => 34.5553,
    'longitude' => 69.2075,
    'risk_level' => 'High',
    'risk_score' => 95,
    'trade_index' => 30,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Russia',
    'code' => 'RU',
    'iso3' => 'RUS',
    'capital' => 'Moscow',
    'region' => 'Europe',
    'sub_region' => 'Eastern Europe',
    'currency' => 'RUB',
    'population' => 144000000,
    'gdp' => 2020000000000,
    'latitude' => 55.7558,
    'longitude' => 37.6173,
    'risk_level' => 'High',
    'risk_score' => 76,
    'trade_index' => 71,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Armenia',
    'code' => 'AM',
    'iso3' => 'ARM',
    'capital' => 'Yerevan',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'AMD',
    'population' => 2800000,
    'gdp' => 26000000000,
    'latitude' => 40.1792,
    'longitude' => 44.4991,
    'risk_level' => 'Medium',
    'risk_score' => 44,
    'trade_index' => 62,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Azerbaijan',
    'code' => 'AZ',
    'iso3' => 'AZE',
    'capital' => 'Baku',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'AZN',
    'population' => 10300000,
    'gdp' => 78000000000,
    'latitude' => 40.4093,
    'longitude' => 49.8671,
    'risk_level' => 'Medium',
    'risk_score' => 46,
    'trade_index' => 70,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Georgia',
    'code' => 'GE',
    'iso3' => 'GEO',
    'capital' => 'Tbilisi',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'GEL',
    'population' => 3700000,
    'gdp' => 31000000000,
    'latitude' => 41.7151,
    'longitude' => 44.8271,
    'risk_level' => 'Low',
    'risk_score' => 33,
    'trade_index' => 73,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Cyprus',
    'code' => 'CY',
    'iso3' => 'CYP',
    'capital' => 'Nicosia',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 1260000,
    'gdp' => 34000000000,
    'latitude' => 35.1856,
    'longitude' => 33.3823,
    'risk_level' => 'Low',
    'risk_score' => 21,
    'trade_index' => 85,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Israel',
    'code' => 'IL',
    'iso3' => 'ISR',
    'capital' => 'Jerusalem',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'ILS',
    'population' => 9900000,
    'gdp' => 550000000000,
    'latitude' => 31.7683,
    'longitude' => 35.2137,
    'risk_level' => 'Medium',
    'risk_score' => 58,
    'trade_index' => 89,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Jordan',
    'code' => 'JO',
    'iso3' => 'JOR',
    'capital' => 'Amman',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'JOD',
    'population' => 11500000,
    'gdp' => 52000000000,
    'latitude' => 31.9454,
    'longitude' => 35.9284,
    'risk_level' => 'Medium',
    'risk_score' => 47,
    'trade_index' => 70,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Lebanon',
    'code' => 'LB',
    'iso3' => 'LBN',
    'capital' => 'Beirut',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'LBP',
    'population' => 5600000,
    'gdp' => 21000000000,
    'latitude' => 33.8938,
    'longitude' => 35.5018,
    'risk_level' => 'High',
    'risk_score' => 78,
    'trade_index' => 52,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Syria',
    'code' => 'SY',
    'iso3' => 'SYR',
    'capital' => 'Damascus',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'SYP',
    'population' => 23800000,
    'gdp' => 23000000000,
    'latitude' => 33.5138,
    'longitude' => 36.2765,
    'risk_level' => 'High',
    'risk_score' => 92,
    'trade_index' => 35,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Closed',
],

[
    'name' => 'Yemen',
    'code' => 'YE',
    'iso3' => 'YEM',
    'capital' => 'Sana\'a',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'YER',
    'population' => 40500000,
    'gdp' => 22000000000,
    'latitude' => 15.3694,
    'longitude' => 44.1910,
    'risk_level' => 'High',
    'risk_score' => 95,
    'trade_index' => 28,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Closed',
],

[
    'name' => 'Palestine',
    'code' => 'PS',
    'iso3' => 'PSE',
    'capital' => 'East Jerusalem',
    'region' => 'Asia',
    'sub_region' => 'Western Asia',
    'currency' => 'ILS',
    'population' => 5500000,
    'gdp' => 19000000000,
    'latitude' => 31.9522,
    'longitude' => 35.2332,
    'risk_level' => 'High',
    'risk_score' => 88,
    'trade_index' => 40,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Bhutan',
    'code' => 'BT',
    'iso3' => 'BTN',
    'capital' => 'Thimphu',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'BTN',
    'population' => 790000,
    'gdp' => 3200000000,
    'latitude' => 27.4728,
    'longitude' => 89.6390,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Maldives',
    'code' => 'MV',
    'iso3' => 'MDV',
    'capital' => 'Malé',
    'region' => 'Asia',
    'sub_region' => 'Southern Asia',
    'currency' => 'MVR',
    'population' => 530000,
    'gdp' => 7000000000,
    'latitude' => 4.1755,
    'longitude' => 73.5093,
    'risk_level' => 'Low',
    'risk_score' => 26,
    'trade_index' => 68,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'North Korea',
    'code' => 'KP',
    'iso3' => 'PRK',
    'capital' => 'Pyongyang',
    'region' => 'Asia',
    'sub_region' => 'Eastern Asia',
    'currency' => 'KPW',
    'population' => 26200000,
    'gdp' => 40000000000,
    'latitude' => 39.0392,
    'longitude' => 125.7625,
    'risk_level' => 'High',
    'risk_score' => 90,
    'trade_index' => 25,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Taiwan',
    'code' => 'TW',
    'iso3' => 'TWN',
    'capital' => 'Taipei',
    'region' => 'Asia',
    'sub_region' => 'Eastern Asia',
    'currency' => 'TWD',
    'population' => 23500000,
    'gdp' => 790000000000,
    'latitude' => 25.0330,
    'longitude' => 121.5654,
    'risk_level' => 'Low',
    'risk_score' => 29,
    'trade_index' => 94,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Germany',
    'code' => 'DE',
    'iso3' => 'DEU',
    'capital' => 'Berlin',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 84500000,
    'gdp' => 4526000000000,
    'latitude' => 52.5200,
    'longitude' => 13.4050,
    'risk_level' => 'Low',
    'risk_score' => 15,
    'trade_index' => 97,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'France',
    'code' => 'FR',
    'iso3' => 'FRA',
    'capital' => 'Paris',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 68500000,
    'gdp' => 3052000000000,
    'latitude' => 48.8566,
    'longitude' => 2.3522,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'United Kingdom',
    'code' => 'GB',
    'iso3' => 'GBR',
    'capital' => 'London',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'GBP',
    'population' => 69000000,
    'gdp' => 3380000000000,
    'latitude' => 51.5074,
    'longitude' => -0.1278,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 94,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Italy',
    'code' => 'IT',
    'iso3' => 'ITA',
    'capital' => 'Rome',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 58900000,
    'gdp' => 2300000000000,
    'latitude' => 41.9028,
    'longitude' => 12.4964,
    'risk_level' => 'Low',
    'risk_score' => 22,
    'trade_index' => 91,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Spain',
    'code' => 'ES',
    'iso3' => 'ESP',
    'capital' => 'Madrid',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 48900000,
    'gdp' => 1620000000000,
    'latitude' => 40.4168,
    'longitude' => -3.7038,
    'risk_level' => 'Low',
    'risk_score' => 21,
    'trade_index' => 90,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Portugal',
    'code' => 'PT',
    'iso3' => 'PRT',
    'capital' => 'Lisbon',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 10500000,
    'gdp' => 301000000000,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'risk_level' => 'Low',
    'risk_score' => 17,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Netherlands',
    'code' => 'NL',
    'iso3' => 'NLD',
    'capital' => 'Amsterdam',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 18000000,
    'gdp' => 1150000000000,
    'latitude' => 52.3676,
    'longitude' => 4.9041,
    'risk_level' => 'Low',
    'risk_score' => 16,
    'trade_index' => 98,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Belgium',
    'code' => 'BE',
    'iso3' => 'BEL',
    'capital' => 'Brussels',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 11900000,
    'gdp' => 655000000000,
    'latitude' => 50.8503,
    'longitude' => 4.3517,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 92,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Luxembourg',
    'code' => 'LU',
    'iso3' => 'LUX',
    'capital' => 'Luxembourg',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 680000,
    'gdp' => 94000000000,
    'latitude' => 49.6116,
    'longitude' => 6.1319,
    'risk_level' => 'Low',
    'risk_score' => 12,
    'trade_index' => 96,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Switzerland',
    'code' => 'CH',
    'iso3' => 'CHE',
    'capital' => 'Bern',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'CHF',
    'population' => 9000000,
    'gdp' => 885000000000,
    'latitude' => 46.9480,
    'longitude' => 7.4474,
    'risk_level' => 'Low',
    'risk_score' => 10,
    'trade_index' => 99,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Austria',
    'code' => 'AT',
    'iso3' => 'AUT',
    'capital' => 'Vienna',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 9100000,
    'gdp' => 530000000000,
    'latitude' => 48.2082,
    'longitude' => 16.3738,
    'risk_level' => 'Low',
    'risk_score' => 14,
    'trade_index' => 92,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Ireland',
    'code' => 'IE',
    'iso3' => 'IRL',
    'capital' => 'Dublin',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'EUR',
    'population' => 5300000,
    'gdp' => 590000000000,
    'latitude' => 53.3498,
    'longitude' => -6.2603,
    'risk_level' => 'Low',
    'risk_score' => 15,
    'trade_index' => 94,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Denmark',
    'code' => 'DK',
    'iso3' => 'DNK',
    'capital' => 'Copenhagen',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'DKK',
    'population' => 6000000,
    'gdp' => 410000000000,
    'latitude' => 55.6761,
    'longitude' => 12.5683,
    'risk_level' => 'Low',
    'risk_score' => 12,
    'trade_index' => 96,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Norway',
    'code' => 'NO',
    'iso3' => 'NOR',
    'capital' => 'Oslo',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'NOK',
    'population' => 5600000,
    'gdp' => 500000000000,
    'latitude' => 59.9139,
    'longitude' => 10.7522,
    'risk_level' => 'Low',
    'risk_score' => 11,
    'trade_index' => 97,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Sweden',
    'code' => 'SE',
    'iso3' => 'SWE',
    'capital' => 'Stockholm',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'SEK',
    'population' => 10600000,
    'gdp' => 610000000000,
    'latitude' => 59.3293,
    'longitude' => 18.0686,
    'risk_level' => 'Low',
    'risk_score' => 13,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Finland',
    'code' => 'FI',
    'iso3' => 'FIN',
    'capital' => 'Helsinki',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'EUR',
    'population' => 5600000,
    'gdp' => 320000000000,
    'latitude' => 60.1699,
    'longitude' => 24.9384,
    'risk_level' => 'Low',
    'risk_score' => 10,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Iceland',
    'code' => 'IS',
    'iso3' => 'ISL',
    'capital' => 'Reykjavik',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'ISK',
    'population' => 400000,
    'gdp' => 33000000000,
    'latitude' => 64.1466,
    'longitude' => -21.9426,
    'risk_level' => 'Low',
    'risk_score' => 9,
    'trade_index' => 94,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Poland',
    'code' => 'PL',
    'iso3' => 'POL',
    'capital' => 'Warsaw',
    'region' => 'Europe',
    'sub_region' => 'Central Europe',
    'currency' => 'PLN',
    'population' => 37800000,
    'gdp' => 842000000000,
    'latitude' => 52.2297,
    'longitude' => 21.0122,
    'risk_level' => 'Low',
    'risk_score' => 23,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Czech Republic',
    'code' => 'CZ',
    'iso3' => 'CZE',
    'capital' => 'Prague',
    'region' => 'Europe',
    'sub_region' => 'Central Europe',
    'currency' => 'CZK',
    'population' => 10900000,
    'gdp' => 343000000000,
    'latitude' => 50.0755,
    'longitude' => 14.4378,
    'risk_level' => 'Low',
    'risk_score' => 19,
    'trade_index' => 90,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Slovakia',
    'code' => 'SK',
    'iso3' => 'SVK',
    'capital' => 'Bratislava',
    'region' => 'Europe',
    'sub_region' => 'Central Europe',
    'currency' => 'EUR',
    'population' => 5500000,
    'gdp' => 145000000000,
    'latitude' => 48.1486,
    'longitude' => 17.1077,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 87,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Hungary',
    'code' => 'HU',
    'iso3' => 'HUN',
    'capital' => 'Budapest',
    'region' => 'Europe',
    'sub_region' => 'Central Europe',
    'currency' => 'HUF',
    'population' => 9600000,
    'gdp' => 212000000000,
    'latitude' => 47.4979,
    'longitude' => 19.0402,
    'risk_level' => 'Low',
    'risk_score' => 22,
    'trade_index' => 86,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Romania',
    'code' => 'RO',
    'iso3' => 'ROU',
    'capital' => 'Bucharest',
    'region' => 'Europe',
    'sub_region' => 'Eastern Europe',
    'currency' => 'RON',
    'population' => 19000000,
    'gdp' => 382000000000,
    'latitude' => 44.4268,
    'longitude' => 26.1025,
    'risk_level' => 'Low',
    'risk_score' => 26,
    'trade_index' => 82,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Bulgaria',
    'code' => 'BG',
    'iso3' => 'BGR',
    'capital' => 'Sofia',
    'region' => 'Europe',
    'sub_region' => 'Eastern Europe',
    'currency' => 'BGN',
    'population' => 6400000,
    'gdp' => 108000000000,
    'latitude' => 42.6977,
    'longitude' => 23.3219,
    'risk_level' => 'Low',
    'risk_score' => 25,
    'trade_index' => 80,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Greece',
    'code' => 'GR',
    'iso3' => 'GRC',
    'capital' => 'Athens',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 10300000,
    'gdp' => 255000000000,
    'latitude' => 37.9838,
    'longitude' => 23.7275,
    'risk_level' => 'Low',
    'risk_score' => 23,
    'trade_index' => 84,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Croatia',
    'code' => 'HR',
    'iso3' => 'HRV',
    'capital' => 'Zagreb',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 3900000,
    'gdp' => 84000000000,
    'latitude' => 45.8150,
    'longitude' => 15.9819,
    'risk_level' => 'Low',
    'risk_score' => 19,
    'trade_index' => 85,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Slovenia',
    'code' => 'SI',
    'iso3' => 'SVN',
    'capital' => 'Ljubljana',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 2120000,
    'gdp' => 72000000000,
    'latitude' => 46.0569,
    'longitude' => 14.5058,
    'risk_level' => 'Low',
    'risk_score' => 17,
    'trade_index' => 89,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Serbia',
    'code' => 'RS',
    'iso3' => 'SRB',
    'capital' => 'Belgrade',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'RSD',
    'population' => 6600000,
    'gdp' => 81000000000,
    'latitude' => 44.7866,
    'longitude' => 20.4489,
    'risk_level' => 'Medium',
    'risk_score' => 37,
    'trade_index' => 74,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Bosnia and Herzegovina',
    'code' => 'BA',
    'iso3' => 'BIH',
    'capital' => 'Sarajevo',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'BAM',
    'population' => 3200000,
    'gdp' => 29000000000,
    'latitude' => 43.8563,
    'longitude' => 18.4131,
    'risk_level' => 'Medium',
    'risk_score' => 40,
    'trade_index' => 70,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Montenegro',
    'code' => 'ME',
    'iso3' => 'MNE',
    'capital' => 'Podgorica',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 620000,
    'gdp' => 8000000000,
    'latitude' => 42.4304,
    'longitude' => 19.2594,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 72,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Albania',
    'code' => 'AL',
    'iso3' => 'ALB',
    'capital' => 'Tirana',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'ALL',
    'population' => 2800000,
    'gdp' => 27000000000,
    'latitude' => 41.3275,
    'longitude' => 19.8187,
    'risk_level' => 'Low',
    'risk_score' => 28,
    'trade_index' => 69,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'North Macedonia',
    'code' => 'MK',
    'iso3' => 'MKD',
    'capital' => 'Skopje',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'MKD',
    'population' => 1830000,
    'gdp' => 16000000000,
    'latitude' => 41.9981,
    'longitude' => 21.4254,
    'risk_level' => 'Low',
    'risk_score' => 27,
    'trade_index' => 68,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Moldova',
    'code' => 'MD',
    'iso3' => 'MDA',
    'capital' => 'Chișinău',
    'region' => 'Europe',
    'sub_region' => 'Eastern Europe',
    'currency' => 'MDL',
    'population' => 2510000,
    'gdp' => 17000000000,
    'latitude' => 47.0105,
    'longitude' => 28.8638,
    'risk_level' => 'Medium',
    'risk_score' => 42,
    'trade_index' => 63,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Ukraine',
    'code' => 'UA',
    'iso3' => 'UKR',
    'capital' => 'Kyiv',
    'region' => 'Europe',
    'sub_region' => 'Eastern Europe',
    'currency' => 'UAH',
    'population' => 36700000,
    'gdp' => 179000000000,
    'latitude' => 50.4501,
    'longitude' => 30.5234,
    'risk_level' => 'High',
    'risk_score' => 89,
    'trade_index' => 58,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Belarus',
    'code' => 'BY',
    'iso3' => 'BLR',
    'capital' => 'Minsk',
    'region' => 'Europe',
    'sub_region' => 'Eastern Europe',
    'currency' => 'BYN',
    'population' => 9200000,
    'gdp' => 71000000000,
    'latitude' => 53.9006,
    'longitude' => 27.5590,
    'risk_level' => 'Medium',
    'risk_score' => 54,
    'trade_index' => 66,
    'supply_status' => 'Normal',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Lithuania',
    'code' => 'LT',
    'iso3' => 'LTU',
    'capital' => 'Vilnius',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'EUR',
    'population' => 2890000,
    'gdp' => 79000000000,
    'latitude' => 54.6872,
    'longitude' => 25.2797,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Latvia',
    'code' => 'LV',
    'iso3' => 'LVA',
    'capital' => 'Riga',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'EUR',
    'population' => 1870000,
    'gdp' => 46000000000,
    'latitude' => 56.9496,
    'longitude' => 24.1052,
    'risk_level' => 'Low',
    'risk_score' => 19,
    'trade_index' => 87,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Estonia',
    'code' => 'EE',
    'iso3' => 'EST',
    'capital' => 'Tallinn',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'EUR',
    'population' => 1370000,
    'gdp' => 43000000000,
    'latitude' => 59.4370,
    'longitude' => 24.7536,
    'risk_level' => 'Low',
    'risk_score' => 15,
    'trade_index' => 91,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Malta',
    'code' => 'MT',
    'iso3' => 'MLT',
    'capital' => 'Valletta',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 570000,
    'gdp' => 27000000000,
    'latitude' => 35.8989,
    'longitude' => 14.5146,
    'risk_level' => 'Low',
    'risk_score' => 13,
    'trade_index' => 89,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Andorra',
    'code' => 'AD',
    'iso3' => 'AND',
    'capital' => 'Andorra la Vella',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 82000,
    'gdp' => 4000000000,
    'latitude' => 42.5063,
    'longitude' => 1.5218,
    'risk_level' => 'Low',
    'risk_score' => 9,
    'trade_index' => 86,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Monaco',
    'code' => 'MC',
    'iso3' => 'MCO',
    'capital' => 'Monaco',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 39000,
    'gdp' => 9000000000,
    'latitude' => 43.7384,
    'longitude' => 7.4246,
    'risk_level' => 'Low',
    'risk_score' => 8,
    'trade_index' => 93,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Liechtenstein',
    'code' => 'LI',
    'iso3' => 'LIE',
    'capital' => 'Vaduz',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'CHF',
    'population' => 40000,
    'gdp' => 7000000000,
    'latitude' => 47.1410,
    'longitude' => 9.5209,
    'risk_level' => 'Low',
    'risk_score' => 8,
    'trade_index' => 90,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'San Marino',
    'code' => 'SM',
    'iso3' => 'SMR',
    'capital' => 'San Marino',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 34000,
    'gdp' => 2100000000,
    'latitude' => 43.9424,
    'longitude' => 12.4578,
    'risk_level' => 'Low',
    'risk_score' => 7,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Vatican City',
    'code' => 'VA',
    'iso3' => 'VAT',
    'capital' => 'Vatican City',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 882,
    'gdp' => 0,
    'latitude' => 41.9029,
    'longitude' => 12.4534,
    'risk_level' => 'Low',
    'risk_score' => 5,
    'trade_index' => 82,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Liechtenstein',
    'code' => 'LI',
    'iso3' => 'LIE',
    'capital' => 'Vaduz',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'CHF',
    'population' => 40000,
    'gdp' => 7000000000,
    'latitude' => 47.1410,
    'longitude' => 9.5209,
    'risk_level' => 'Low',
    'risk_score' => 8,
    'trade_index' => 90,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Malta',
    'code' => 'MT',
    'iso3' => 'MLT',
    'capital' => 'Valletta',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 570000,
    'gdp' => 27000000000,
    'latitude' => 35.8989,
    'longitude' => 14.5146,
    'risk_level' => 'Low',
    'risk_score' => 13,
    'trade_index' => 89,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Belgium',
    'code' => 'BE',
    'iso3' => 'BEL',
    'capital' => 'Brussels',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 11900000,
    'gdp' => 655000000000,
    'latitude' => 50.8503,
    'longitude' => 4.3517,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 92,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Netherlands',
    'code' => 'NL',
    'iso3' => 'NLD',
    'capital' => 'Amsterdam',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 18000000,
    'gdp' => 1150000000000,
    'latitude' => 52.3676,
    'longitude' => 4.9041,
    'risk_level' => 'Low',
    'risk_score' => 16,
    'trade_index' => 98,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Portugal',
    'code' => 'PT',
    'iso3' => 'PRT',
    'capital' => 'Lisbon',
    'region' => 'Europe',
    'sub_region' => 'Southern Europe',
    'currency' => 'EUR',
    'population' => 10500000,
    'gdp' => 301000000000,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'risk_level' => 'Low',
    'risk_score' => 17,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Austria',
    'code' => 'AT',
    'iso3' => 'AUT',
    'capital' => 'Vienna',
    'region' => 'Europe',
    'sub_region' => 'Western Europe',
    'currency' => 'EUR',
    'population' => 9100000,
    'gdp' => 530000000000,
    'latitude' => 48.2082,
    'longitude' => 16.3738,
    'risk_level' => 'Low',
    'risk_score' => 14,
    'trade_index' => 92,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Ireland',
    'code' => 'IE',
    'iso3' => 'IRL',
    'capital' => 'Dublin',
    'region' => 'Europe',
    'sub_region' => 'Northern Europe',
    'currency' => 'EUR',
    'population' => 5300000,
    'gdp' => 590000000000,
    'latitude' => 53.3498,
    'longitude' => -6.2603,
    'risk_level' => 'Low',
    'risk_score' => 15,
    'trade_index' => 94,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Algeria',
    'code' => 'DZ',
    'iso3' => 'DZA',
    'capital' => 'Algiers',
    'region' => 'Africa',
    'sub_region' => 'Northern Africa',
    'currency' => 'DZD',
    'population' => 46200000,
    'gdp' => 266000000000,
    'latitude' => 36.7538,
    'longitude' => 3.0588,
    'risk_level' => 'Medium',
    'risk_score' => 45,
    'trade_index' => 72,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Egypt',
    'code' => 'EG',
    'iso3' => 'EGY',
    'capital' => 'Cairo',
    'region' => 'Africa',
    'sub_region' => 'Northern Africa',
    'currency' => 'EGP',
    'population' => 114000000,
    'gdp' => 396000000000,
    'latitude' => 30.0444,
    'longitude' => 31.2357,
    'risk_level' => 'Medium',
    'risk_score' => 48,
    'trade_index' => 78,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Libya',
    'code' => 'LY',
    'iso3' => 'LBY',
    'capital' => 'Tripoli',
    'region' => 'Africa',
    'sub_region' => 'Northern Africa',
    'currency' => 'LYD',
    'population' => 6900000,
    'gdp' => 50000000000,
    'latitude' => 32.8872,
    'longitude' => 13.1913,
    'risk_level' => 'High',
    'risk_score' => 78,
    'trade_index' => 45,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Tunisia',
    'code' => 'TN',
    'iso3' => 'TUN',
    'capital' => 'Tunis',
    'region' => 'Africa',
    'sub_region' => 'Northern Africa',
    'currency' => 'TND',
    'population' => 12400000,
    'gdp' => 54000000000,
    'latitude' => 36.8065,
    'longitude' => 10.1815,
    'risk_level' => 'Low',
    'risk_score' => 30,
    'trade_index' => 69,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Morocco',
    'code' => 'MA',
    'iso3' => 'MAR',
    'capital' => 'Rabat',
    'region' => 'Africa',
    'sub_region' => 'Northern Africa',
    'currency' => 'MAD',
    'population' => 38000000,
    'gdp' => 152000000000,
    'latitude' => 34.0209,
    'longitude' => -6.8416,
    'risk_level' => 'Low',
    'risk_score' => 29,
    'trade_index' => 74,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Sudan',
    'code' => 'SD',
    'iso3' => 'SDN',
    'capital' => 'Khartoum',
    'region' => 'Africa',
    'sub_region' => 'Northern Africa',
    'currency' => 'SDG',
    'population' => 51000000,
    'gdp' => 34000000000,
    'latitude' => 15.5007,
    'longitude' => 32.5599,
    'risk_level' => 'High',
    'risk_score' => 90,
    'trade_index' => 38,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Closed',
],

[
    'name' => 'South Sudan',
    'code' => 'SS',
    'iso3' => 'SSD',
    'capital' => 'Juba',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'SSP',
    'population' => 11800000,
    'gdp' => 7000000000,
    'latitude' => 4.8594,
    'longitude' => 31.5713,
    'risk_level' => 'High',
    'risk_score' => 93,
    'trade_index' => 30,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Closed',
],

[
    'name' => 'Ethiopia',
    'code' => 'ET',
    'iso3' => 'ETH',
    'capital' => 'Addis Ababa',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'ETB',
    'population' => 132000000,
    'gdp' => 205000000000,
    'latitude' => 9.0320,
    'longitude' => 38.7469,
    'risk_level' => 'Medium',
    'risk_score' => 56,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Kenya',
    'code' => 'KE',
    'iso3' => 'KEN',
    'capital' => 'Nairobi',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'KES',
    'population' => 56000000,
    'gdp' => 132000000000,
    'latitude' => -1.2921,
    'longitude' => 36.8219,
    'risk_level' => 'Low',
    'risk_score' => 35,
    'trade_index' => 71,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Tanzania',
    'code' => 'TZ',
    'iso3' => 'TZA',
    'capital' => 'Dodoma',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'TZS',
    'population' => 69000000,
    'gdp' => 86000000000,
    'latitude' => -6.1630,
    'longitude' => 35.7516,
    'risk_level' => 'Low',
    'risk_score' => 36,
    'trade_index' => 68,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Uganda',
    'code' => 'UG',
    'iso3' => 'UGA',
    'capital' => 'Kampala',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'UGX',
    'population' => 50000000,
    'gdp' => 56000000000,
    'latitude' => 0.3476,
    'longitude' => 32.5825,
    'risk_level' => 'Medium',
    'risk_score' => 44,
    'trade_index' => 66,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Rwanda',
    'code' => 'RW',
    'iso3' => 'RWA',
    'capital' => 'Kigali',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'RWF',
    'population' => 14200000,
    'gdp' => 17000000000,
    'latitude' => -1.9441,
    'longitude' => 30.0619,
    'risk_level' => 'Low',
    'risk_score' => 31,
    'trade_index' => 70,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Burundi',
    'code' => 'BI',
    'iso3' => 'BDI',
    'capital' => 'Gitega',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'BIF',
    'population' => 14000000,
    'gdp' => 4000000000,
    'latitude' => -3.4264,
    'longitude' => 29.9306,
    'risk_level' => 'Medium',
    'risk_score' => 58,
    'trade_index' => 42,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Somalia',
    'code' => 'SO',
    'iso3' => 'SOM',
    'capital' => 'Mogadishu',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'SOS',
    'population' => 19600000,
    'gdp' => 13000000000,
    'latitude' => 2.0469,
    'longitude' => 45.3182,
    'risk_level' => 'High',
    'risk_score' => 94,
    'trade_index' => 26,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Closed',
],

[
    'name' => 'Djibouti',
    'code' => 'DJ',
    'iso3' => 'DJI',
    'capital' => 'Djibouti',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'DJF',
    'population' => 1200000,
    'gdp' => 4500000000,
    'latitude' => 11.5721,
    'longitude' => 43.1456,
    'risk_level' => 'Low',
    'risk_score' => 34,
    'trade_index' => 72,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Eritrea',
    'code' => 'ER',
    'iso3' => 'ERI',
    'capital' => 'Asmara',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'ERN',
    'population' => 3700000,
    'gdp' => 2600000000,
    'latitude' => 15.3229,
    'longitude' => 38.9251,
    'risk_level' => 'High',
    'risk_score' => 74,
    'trade_index' => 35,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Seychelles',
    'code' => 'SC',
    'iso3' => 'SYC',
    'capital' => 'Victoria',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'SCR',
    'population' => 121000,
    'gdp' => 2400000000,
    'latitude' => -4.6191,
    'longitude' => 55.4513,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 81,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Mauritius',
    'code' => 'MU',
    'iso3' => 'MUS',
    'capital' => 'Port Louis',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'MUR',
    'population' => 1260000,
    'gdp' => 17000000000,
    'latitude' => -20.1609,
    'longitude' => 57.5012,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 84,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Madagascar',
    'code' => 'MG',
    'iso3' => 'MDG',
    'capital' => 'Antananarivo',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'MGA',
    'population' => 32000000,
    'gdp' => 18000000000,
    'latitude' => -18.8792,
    'longitude' => 47.5079,
    'risk_level' => 'Medium',
    'risk_score' => 52,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Comoros',
    'code' => 'KM',
    'iso3' => 'COM',
    'capital' => 'Moroni',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'KMF',
    'population' => 890000,
    'gdp' => 1400000000,
    'latitude' => -11.7172,
    'longitude' => 43.2473,
    'risk_level' => 'Medium',
    'risk_score' => 49,
    'trade_index' => 46,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Mozambique',
    'code' => 'MZ',
    'iso3' => 'MOZ',
    'capital' => 'Maputo',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'MZN',
    'population' => 34500000,
    'gdp' => 22000000000,
    'latitude' => -25.9692,
    'longitude' => 32.5732,
    'risk_level' => 'Medium',
    'risk_score' => 56,
    'trade_index' => 58,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Zambia',
    'code' => 'ZM',
    'iso3' => 'ZMB',
    'capital' => 'Lusaka',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'ZMW',
    'population' => 21200000,
    'gdp' => 32000000000,
    'latitude' => -15.3875,
    'longitude' => 28.3228,
    'risk_level' => 'Medium',
    'risk_score' => 48,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Zimbabwe',
    'code' => 'ZW',
    'iso3' => 'ZWE',
    'capital' => 'Harare',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'ZiG',
    'population' => 17100000,
    'gdp' => 35000000000,
    'latitude' => -17.8252,
    'longitude' => 31.0335,
    'risk_level' => 'Medium',
    'risk_score' => 60,
    'trade_index' => 54,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Malawi',
    'code' => 'MW',
    'iso3' => 'MWI',
    'capital' => 'Lilongwe',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'MWK',
    'population' => 22000000,
    'gdp' => 14000000000,
    'latitude' => -13.9626,
    'longitude' => 33.7741,
    'risk_level' => 'Medium',
    'risk_score' => 57,
    'trade_index' => 49,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Angola',
    'code' => 'AO',
    'iso3' => 'AGO',
    'capital' => 'Luanda',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'AOA',
    'population' => 39000000,
    'gdp' => 113000000000,
    'latitude' => -8.8390,
    'longitude' => 13.2894,
    'risk_level' => 'Medium',
    'risk_score' => 53,
    'trade_index' => 63,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Namibia',
    'code' => 'NA',
    'iso3' => 'NAM',
    'capital' => 'Windhoek',
    'region' => 'Africa',
    'sub_region' => 'Southern Africa',
    'currency' => 'NAD',
    'population' => 3100000,
    'gdp' => 14000000000,
    'latitude' => -22.5609,
    'longitude' => 17.0658,
    'risk_level' => 'Low',
    'risk_score' => 32,
    'trade_index' => 67,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Botswana',
    'code' => 'BW',
    'iso3' => 'BWA',
    'capital' => 'Gaborone',
    'region' => 'Africa',
    'sub_region' => 'Southern Africa',
    'currency' => 'BWP',
    'population' => 2600000,
    'gdp' => 22000000000,
    'latitude' => -24.6282,
    'longitude' => 25.9231,
    'risk_level' => 'Low',
    'risk_score' => 28,
    'trade_index' => 73,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'South Africa',
    'code' => 'ZA',
    'iso3' => 'ZAF',
    'capital' => 'Pretoria',
    'region' => 'Africa',
    'sub_region' => 'Southern Africa',
    'currency' => 'ZAR',
    'population' => 64000000,
    'gdp' => 410000000000,
    'latitude' => -25.7479,
    'longitude' => 28.2293,
    'risk_level' => 'Medium',
    'risk_score' => 42,
    'trade_index' => 82,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Lesotho',
    'code' => 'LS',
    'iso3' => 'LSO',
    'capital' => 'Maseru',
    'region' => 'Africa',
    'sub_region' => 'Southern Africa',
    'currency' => 'LSL',
    'population' => 2400000,
    'gdp' => 2900000000,
    'latitude' => -29.3158,
    'longitude' => 27.4869,
    'risk_level' => 'Low',
    'risk_score' => 35,
    'trade_index' => 51,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Eswatini',
    'code' => 'SZ',
    'iso3' => 'SWZ',
    'capital' => 'Mbabane',
    'region' => 'Africa',
    'sub_region' => 'Southern Africa',
    'currency' => 'SZL',
    'population' => 1250000,
    'gdp' => 5000000000,
    'latitude' => -26.3054,
    'longitude' => 31.1367,
    'risk_level' => 'Low',
    'risk_score' => 34,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Nigeria',
    'code' => 'NG',
    'iso3' => 'NGA',
    'capital' => 'Abuja',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'NGN',
    'population' => 232000000,
    'gdp' => 363000000000,
    'latitude' => 9.0765,
    'longitude' => 7.3986,
    'risk_level' => 'Medium',
    'risk_score' => 59,
    'trade_index' => 76,
    'supply_status' => 'Normal',
    'shipping_status' => 'Busy',
],

[
    'name' => 'Ghana',
    'code' => 'GH',
    'iso3' => 'GHA',
    'capital' => 'Accra',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'GHS',
    'population' => 34500000,
    'gdp' => 76000000000,
    'latitude' => 5.6037,
    'longitude' => -0.1870,
    'risk_level' => 'Low',
    'risk_score' => 37,
    'trade_index' => 71,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Côte d\'Ivoire',
    'code' => 'CI',
    'iso3' => 'CIV',
    'capital' => 'Yamoussoukro',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 32000000,
    'gdp' => 87000000000,
    'latitude' => 6.8276,
    'longitude' => -5.2893,
    'risk_level' => 'Medium',
    'risk_score' => 46,
    'trade_index' => 69,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Senegal',
    'code' => 'SN',
    'iso3' => 'SEN',
    'capital' => 'Dakar',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 18800000,
    'gdp' => 35000000000,
    'latitude' => 14.7167,
    'longitude' => -17.4677,
    'risk_level' => 'Low',
    'risk_score' => 34,
    'trade_index' => 68,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Mali',
    'code' => 'ML',
    'iso3' => 'MLI',
    'capital' => 'Bamako',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 24500000,
    'gdp' => 22000000000,
    'latitude' => 12.6392,
    'longitude' => -8.0029,
    'risk_level' => 'High',
    'risk_score' => 77,
    'trade_index' => 43,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Burkina Faso',
    'code' => 'BF',
    'iso3' => 'BFA',
    'capital' => 'Ouagadougou',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 23800000,
    'gdp' => 22000000000,
    'latitude' => 12.3714,
    'longitude' => -1.5197,
    'risk_level' => 'High',
    'risk_score' => 79,
    'trade_index' => 41,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Niger',
    'code' => 'NE',
    'iso3' => 'NER',
    'capital' => 'Niamey',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 28000000,
    'gdp' => 19000000000,
    'latitude' => 13.5116,
    'longitude' => 2.1254,
    'risk_level' => 'High',
    'risk_score' => 82,
    'trade_index' => 39,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Benin',
    'code' => 'BJ',
    'iso3' => 'BEN',
    'capital' => 'Porto-Novo',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 14600000,
    'gdp' => 21000000000,
    'latitude' => 6.4969,
    'longitude' => 2.6289,
    'risk_level' => 'Medium',
    'risk_score' => 45,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Togo',
    'code' => 'TG',
    'iso3' => 'TGO',
    'capital' => 'Lomé',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 9500000,
    'gdp' => 9500000000,
    'latitude' => 6.1375,
    'longitude' => 1.2123,
    'risk_level' => 'Medium',
    'risk_score' => 44,
    'trade_index' => 58,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Guinea',
    'code' => 'GN',
    'iso3' => 'GIN',
    'capital' => 'Conakry',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'GNF',
    'population' => 15200000,
    'gdp' => 24000000000,
    'latitude' => 9.6412,
    'longitude' => -13.5784,
    'risk_level' => 'Medium',
    'risk_score' => 55,
    'trade_index' => 53,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Guinea-Bissau',
    'code' => 'GW',
    'iso3' => 'GNB',
    'capital' => 'Bissau',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'XOF',
    'population' => 2200000,
    'gdp' => 2100000000,
    'latitude' => 11.8817,
    'longitude' => -15.6170,
    'risk_level' => 'Medium',
    'risk_score' => 57,
    'trade_index' => 45,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Sierra Leone',
    'code' => 'SL',
    'iso3' => 'SLE',
    'capital' => 'Freetown',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'SLL',
    'population' => 8900000,
    'gdp' => 4300000000,
    'latitude' => 8.4657,
    'longitude' => -13.2317,
    'risk_level' => 'Medium',
    'risk_score' => 60,
    'trade_index' => 46,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Liberia',
    'code' => 'LR',
    'iso3' => 'LBR',
    'capital' => 'Monrovia',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'LRD',
    'population' => 5600000,
    'gdp' => 4800000000,
    'latitude' => 6.3156,
    'longitude' => -10.8074,
    'risk_level' => 'Medium',
    'risk_score' => 59,
    'trade_index' => 48,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'The Gambia',
    'code' => 'GM',
    'iso3' => 'GMB',
    'capital' => 'Banjul',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'GMD',
    'population' => 2800000,
    'gdp' => 2900000000,
    'latitude' => 13.4549,
    'longitude' => -16.5790,
    'risk_level' => 'Low',
    'risk_score' => 40,
    'trade_index' => 52,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Cabo Verde',
    'code' => 'CV',
    'iso3' => 'CPV',
    'capital' => 'Praia',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'CVE',
    'population' => 610000,
    'gdp' => 2900000000,
    'latitude' => 14.9330,
    'longitude' => -23.5133,
    'risk_level' => 'Low',
    'risk_score' => 25,
    'trade_index' => 65,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Mauritania',
    'code' => 'MR',
    'iso3' => 'MRT',
    'capital' => 'Nouakchott',
    'region' => 'Africa',
    'sub_region' => 'Western Africa',
    'currency' => 'MRU',
    'population' => 5100000,
    'gdp' => 11000000000,
    'latitude' => 18.0735,
    'longitude' => -15.9582,
    'risk_level' => 'Medium',
    'risk_score' => 52,
    'trade_index' => 50,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Cameroon',
    'code' => 'CM',
    'iso3' => 'CMR',
    'capital' => 'Yaoundé',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'XAF',
    'population' => 29500000,
    'gdp' => 54000000000,
    'latitude' => 3.8480,
    'longitude' => 11.5021,
    'risk_level' => 'Medium',
    'risk_score' => 54,
    'trade_index' => 61,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Central African Republic',
    'code' => 'CF',
    'iso3' => 'CAF',
    'capital' => 'Bangui',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'XAF',
    'population' => 5600000,
    'gdp' => 2900000000,
    'latitude' => 4.3947,
    'longitude' => 18.5582,
    'risk_level' => 'High',
    'risk_score' => 91,
    'trade_index' => 27,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Chad',
    'code' => 'TD',
    'iso3' => 'TCD',
    'capital' => 'N\'Djamena',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'XAF',
    'population' => 21200000,
    'gdp' => 14000000000,
    'latitude' => 12.1348,
    'longitude' => 15.0557,
    'risk_level' => 'High',
    'risk_score' => 82,
    'trade_index' => 37,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Republic of the Congo',
    'code' => 'CG',
    'iso3' => 'COG',
    'capital' => 'Brazzaville',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'XAF',
    'population' => 6500000,
    'gdp' => 16000000000,
    'latitude' => -4.2634,
    'longitude' => 15.2429,
    'risk_level' => 'Medium',
    'risk_score' => 58,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Democratic Republic of the Congo',
    'code' => 'CD',
    'iso3' => 'COD',
    'capital' => 'Kinshasa',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'CDF',
    'population' => 112000000,
    'gdp' => 74000000000,
    'latitude' => -4.4419,
    'longitude' => 15.2663,
    'risk_level' => 'High',
    'risk_score' => 86,
    'trade_index' => 44,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Gabon',
    'code' => 'GA',
    'iso3' => 'GAB',
    'capital' => 'Libreville',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'XAF',
    'population' => 2500000,
    'gdp' => 23000000000,
    'latitude' => 0.4162,
    'longitude' => 9.4673,
    'risk_level' => 'Low',
    'risk_score' => 33,
    'trade_index' => 66,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Equatorial Guinea',
    'code' => 'GQ',
    'iso3' => 'GNQ',
    'capital' => 'Malabo',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'XAF',
    'population' => 1900000,
    'gdp' => 12000000000,
    'latitude' => 3.7504,
    'longitude' => 8.7371,
    'risk_level' => 'Medium',
    'risk_score' => 51,
    'trade_index' => 57,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'São Tomé and Príncipe',
    'code' => 'ST',
    'iso3' => 'STP',
    'capital' => 'São Tomé',
    'region' => 'Africa',
    'sub_region' => 'Middle Africa',
    'currency' => 'STN',
    'population' => 240000,
    'gdp' => 700000000,
    'latitude' => 0.3365,
    'longitude' => 6.7273,
    'risk_level' => 'Low',
    'risk_score' => 29,
    'trade_index' => 54,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'South Sudan',
    'code' => 'SS',
    'iso3' => 'SSD',
    'capital' => 'Juba',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'SSP',
    'population' => 11800000,
    'gdp' => 7000000000,
    'latitude' => 4.8594,
    'longitude' => 31.5713,
    'risk_level' => 'High',
    'risk_score' => 93,
    'trade_index' => 30,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Closed',
],

[
    'name' => 'Mozambique',
    'code' => 'MZ',
    'iso3' => 'MOZ',
    'capital' => 'Maputo',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'MZN',
    'population' => 34500000,
    'gdp' => 22000000000,
    'latitude' => -25.9692,
    'longitude' => 32.5732,
    'risk_level' => 'Medium',
    'risk_score' => 56,
    'trade_index' => 58,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Djibouti',
    'code' => 'DJ',
    'iso3' => 'DJI',
    'capital' => 'Djibouti',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'DJF',
    'population' => 1200000,
    'gdp' => 4500000000,
    'latitude' => 11.5721,
    'longitude' => 43.1456,
    'risk_level' => 'Low',
    'risk_score' => 34,
    'trade_index' => 72,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Eritrea',
    'code' => 'ER',
    'iso3' => 'ERI',
    'capital' => 'Asmara',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'ERN',
    'population' => 3700000,
    'gdp' => 2600000000,
    'latitude' => 15.3229,
    'longitude' => 38.9251,
    'risk_level' => 'High',
    'risk_score' => 74,
    'trade_index' => 35,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Mauritius',
    'code' => 'MU',
    'iso3' => 'MUS',
    'capital' => 'Port Louis',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'MUR',
    'population' => 1260000,
    'gdp' => 17000000000,
    'latitude' => -20.1609,
    'longitude' => 57.5012,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 84,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Seychelles',
    'code' => 'SC',
    'iso3' => 'SYC',
    'capital' => 'Victoria',
    'region' => 'Africa',
    'sub_region' => 'Eastern Africa',
    'currency' => 'SCR',
    'population' => 121000,
    'gdp' => 2400000000,
    'latitude' => -4.6191,
    'longitude' => 55.4513,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 81,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'United States',
    'code' => 'US',
    'iso3' => 'USA',
    'capital' => 'Washington, D.C.',
    'region' => 'Americas',
    'sub_region' => 'Northern America',
    'currency' => 'USD',
    'population' => 340000000,
    'gdp' => 29167000000000,
    'latitude' => 38.9072,
    'longitude' => -77.0369,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 100,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Canada',
    'code' => 'CA',
    'iso3' => 'CAN',
    'capital' => 'Ottawa',
    'region' => 'Americas',
    'sub_region' => 'Northern America',
    'currency' => 'CAD',
    'population' => 41000000,
    'gdp' => 2240000000000,
    'latitude' => 45.4215,
    'longitude' => -75.6972,
    'risk_level' => 'Low',
    'risk_score' => 14,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Mexico',
    'code' => 'MX',
    'iso3' => 'MEX',
    'capital' => 'Mexico City',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'MXN',
    'population' => 131000000,
    'gdp' => 2017000000000,
    'latitude' => 19.4326,
    'longitude' => -99.1332,
    'risk_level' => 'Medium',
    'risk_score' => 42,
    'trade_index' => 85,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Guatemala',
    'code' => 'GT',
    'iso3' => 'GTM',
    'capital' => 'Guatemala City',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'GTQ',
    'population' => 18600000,
    'gdp' => 118000000000,
    'latitude' => 14.6349,
    'longitude' => -90.5069,
    'risk_level' => 'Medium',
    'risk_score' => 44,
    'trade_index' => 63,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Belize',
    'code' => 'BZ',
    'iso3' => 'BLZ',
    'capital' => 'Belmopan',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'BZD',
    'population' => 430000,
    'gdp' => 3300000000,
    'latitude' => 17.2510,
    'longitude' => -88.7590,
    'risk_level' => 'Low',
    'risk_score' => 31,
    'trade_index' => 58,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Honduras',
    'code' => 'HN',
    'iso3' => 'HND',
    'capital' => 'Tegucigalpa',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'HNL',
    'population' => 10900000,
    'gdp' => 39000000000,
    'latitude' => 14.0723,
    'longitude' => -87.1921,
    'risk_level' => 'Medium',
    'risk_score' => 49,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'El Salvador',
    'code' => 'SV',
    'iso3' => 'SLV',
    'capital' => 'San Salvador',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'USD',
    'population' => 6400000,
    'gdp' => 36000000000,
    'latitude' => 13.6929,
    'longitude' => -89.2182,
    'risk_level' => 'Low',
    'risk_score' => 35,
    'trade_index' => 61,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Nicaragua',
    'code' => 'NI',
    'iso3' => 'NIC',
    'capital' => 'Managua',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'NIO',
    'population' => 7100000,
    'gdp' => 18000000000,
    'latitude' => 12.1140,
    'longitude' => -86.2362,
    'risk_level' => 'Medium',
    'risk_score' => 46,
    'trade_index' => 52,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Costa Rica',
    'code' => 'CR',
    'iso3' => 'CRI',
    'capital' => 'San José',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'CRC',
    'population' => 5300000,
    'gdp' => 96000000000,
    'latitude' => 9.9281,
    'longitude' => -84.0907,
    'risk_level' => 'Low',
    'risk_score' => 22,
    'trade_index' => 80,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Panama',
    'code' => 'PA',
    'iso3' => 'PAN',
    'capital' => 'Panama City',
    'region' => 'Americas',
    'sub_region' => 'Central America',
    'currency' => 'PAB',
    'population' => 4600000,
    'gdp' => 98000000000,
    'latitude' => 8.9824,
    'longitude' => -79.5199,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 86,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Cuba',
    'code' => 'CU',
    'iso3' => 'CUB',
    'capital' => 'Havana',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'CUP',
    'population' => 10900000,
    'gdp' => 109000000000,
    'latitude' => 23.1136,
    'longitude' => -82.3666,
    'risk_level' => 'Medium',
    'risk_score' => 41,
    'trade_index' => 62,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Jamaica',
    'code' => 'JM',
    'iso3' => 'JAM',
    'capital' => 'Kingston',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'JMD',
    'population' => 2800000,
    'gdp' => 21000000000,
    'latitude' => 17.9712,
    'longitude' => -76.7936,
    'risk_level' => 'Low',
    'risk_score' => 30,
    'trade_index' => 64,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Haiti',
    'code' => 'HT',
    'iso3' => 'HTI',
    'capital' => 'Port-au-Prince',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'HTG',
    'population' => 11800000,
    'gdp' => 21000000000,
    'latitude' => 18.5944,
    'longitude' => -72.3074,
    'risk_level' => 'High',
    'risk_score' => 92,
    'trade_index' => 28,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Dominican Republic',
    'code' => 'DO',
    'iso3' => 'DOM',
    'capital' => 'Santo Domingo',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'DOP',
    'population' => 11500000,
    'gdp' => 145000000000,
    'latitude' => 18.4861,
    'longitude' => -69.9312,
    'risk_level' => 'Low',
    'risk_score' => 33,
    'trade_index' => 73,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Bahamas',
    'code' => 'BS',
    'iso3' => 'BHS',
    'capital' => 'Nassau',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'BSD',
    'population' => 410000,
    'gdp' => 15000000000,
    'latitude' => 25.0443,
    'longitude' => -77.3504,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 67,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Barbados',
    'code' => 'BB',
    'iso3' => 'BRB',
    'capital' => 'Bridgetown',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'BBD',
    'population' => 282000,
    'gdp' => 6400000000,
    'latitude' => 13.0975,
    'longitude' => -59.6165,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 71,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Trinidad and Tobago',
    'code' => 'TT',
    'iso3' => 'TTO',
    'capital' => 'Port of Spain',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'TTD',
    'population' => 1500000,
    'gdp' => 31000000000,
    'latitude' => 10.6549,
    'longitude' => -61.5019,
    'risk_level' => 'Low',
    'risk_score' => 27,
    'trade_index' => 74,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Antigua and Barbuda',
    'code' => 'AG',
    'iso3' => 'ATG',
    'capital' => 'Saint John\'s',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'XCD',
    'population' => 94000,
    'gdp' => 2200000000,
    'latitude' => 17.1274,
    'longitude' => -61.8468,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 63,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Dominica',
    'code' => 'DM',
    'iso3' => 'DMA',
    'capital' => 'Roseau',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'XCD',
    'population' => 72000,
    'gdp' => 700000000,
    'latitude' => 15.3092,
    'longitude' => -61.3794,
    'risk_level' => 'Low',
    'risk_score' => 19,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Saint Lucia',
    'code' => 'LC',
    'iso3' => 'LCA',
    'capital' => 'Castries',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'XCD',
    'population' => 180000,
    'gdp' => 2800000000,
    'latitude' => 14.0101,
    'longitude' => -60.9875,
    'risk_level' => 'Low',
    'risk_score' => 22,
    'trade_index' => 62,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Saint Vincent and the Grenadines',
    'code' => 'VC',
    'iso3' => 'VCT',
    'capital' => 'Kingstown',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'XCD',
    'population' => 111000,
    'gdp' => 1100000000,
    'latitude' => 13.1600,
    'longitude' => -61.2248,
    'risk_level' => 'Low',
    'risk_score' => 21,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Grenada',
    'code' => 'GD',
    'iso3' => 'GRD',
    'capital' => 'Saint George\'s',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'XCD',
    'population' => 126000,
    'gdp' => 1500000000,
    'latitude' => 12.0561,
    'longitude' => -61.7488,
    'risk_level' => 'Low',
    'risk_score' => 20,
    'trade_index' => 61,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Saint Kitts and Nevis',
    'code' => 'KN',
    'iso3' => 'KNA',
    'capital' => 'Basseterre',
    'region' => 'Americas',
    'sub_region' => 'Caribbean',
    'currency' => 'XCD',
    'population' => 48000,
    'gdp' => 1200000000,
    'latitude' => 17.3026,
    'longitude' => -62.7177,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 62,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Argentina',
    'code' => 'AR',
    'iso3' => 'ARG',
    'capital' => 'Buenos Aires',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'ARS',
    'population' => 47000000,
    'gdp' => 640000000000,
    'latitude' => -34.6037,
    'longitude' => -58.3816,
    'risk_level' => 'Medium',
    'risk_score' => 39,
    'trade_index' => 79,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Brazil',
    'code' => 'BR',
    'iso3' => 'BRA',
    'capital' => 'Brasília',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'BRL',
    'population' => 212000000,
    'gdp' => 2180000000000,
    'latitude' => -15.7939,
    'longitude' => -47.8828,
    'risk_level' => 'Medium',
    'risk_score' => 35,
    'trade_index' => 87,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Chile',
    'code' => 'CL',
    'iso3' => 'CHL',
    'capital' => 'Santiago',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'CLP',
    'population' => 19800000,
    'gdp' => 340000000000,
    'latitude' => -33.4489,
    'longitude' => -70.6693,
    'risk_level' => 'Low',
    'risk_score' => 23,
    'trade_index' => 88,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Uruguay',
    'code' => 'UY',
    'iso3' => 'URY',
    'capital' => 'Montevideo',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'UYU',
    'population' => 3400000,
    'gdp' => 77000000000,
    'latitude' => -34.9011,
    'longitude' => -56.1645,
    'risk_level' => 'Low',
    'risk_score' => 18,
    'trade_index' => 84,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Paraguay',
    'code' => 'PY',
    'iso3' => 'PRY',
    'capital' => 'Asunción',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'PYG',
    'population' => 6900000,
    'gdp' => 45000000000,
    'latitude' => -25.2637,
    'longitude' => -57.5759,
    'risk_level' => 'Low',
    'risk_score' => 29,
    'trade_index' => 68,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Bolivia',
    'code' => 'BO',
    'iso3' => 'BOL',
    'capital' => 'Sucre',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'BOB',
    'population' => 12500000,
    'gdp' => 47000000000,
    'latitude' => -19.0196,
    'longitude' => -65.2619,
    'risk_level' => 'Medium',
    'risk_score' => 42,
    'trade_index' => 59,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Peru',
    'code' => 'PE',
    'iso3' => 'PER',
    'capital' => 'Lima',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'PEN',
    'population' => 35000000,
    'gdp' => 270000000000,
    'latitude' => -12.0464,
    'longitude' => -77.0428,
    'risk_level' => 'Medium',
    'risk_score' => 34,
    'trade_index' => 77,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Colombia',
    'code' => 'CO',
    'iso3' => 'COL',
    'capital' => 'Bogotá',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'COP',
    'population' => 53000000,
    'gdp' => 386000000000,
    'latitude' => 4.7110,
    'longitude' => -74.0721,
    'risk_level' => 'Medium',
    'risk_score' => 37,
    'trade_index' => 80,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Venezuela',
    'code' => 'VE',
    'iso3' => 'VEN',
    'capital' => 'Caracas',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'VES',
    'population' => 29000000,
    'gdp' => 106000000000,
    'latitude' => 10.4806,
    'longitude' => -66.9036,
    'risk_level' => 'High',
    'risk_score' => 72,
    'trade_index' => 48,
    'supply_status' => 'Delayed',
    'shipping_status' => 'Limited',
],

[
    'name' => 'Ecuador',
    'code' => 'EC',
    'iso3' => 'ECU',
    'capital' => 'Quito',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'USD',
    'population' => 18500000,
    'gdp' => 125000000000,
    'latitude' => -0.1807,
    'longitude' => -78.4678,
    'risk_level' => 'Medium',
    'risk_score' => 43,
    'trade_index' => 72,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Guyana',
    'code' => 'GY',
    'iso3' => 'GUY',
    'capital' => 'Georgetown',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'GYD',
    'population' => 840000,
    'gdp' => 25000000000,
    'latitude' => 6.8013,
    'longitude' => -58.1551,
    'risk_level' => 'Low',
    'risk_score' => 26,
    'trade_index' => 66,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Suriname',
    'code' => 'SR',
    'iso3' => 'SUR',
    'capital' => 'Paramaribo',
    'region' => 'Americas',
    'sub_region' => 'South America',
    'currency' => 'SRD',
    'population' => 640000,
    'gdp' => 4500000000,
    'latitude' => 5.8520,
    'longitude' => -55.2038,
    'risk_level' => 'Low',
    'risk_score' => 28,
    'trade_index' => 60,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Australia',
    'code' => 'AU',
    'iso3' => 'AUS',
    'capital' => 'Canberra',
    'region' => 'Oceania',
    'sub_region' => 'Australia and New Zealand',
    'currency' => 'AUD',
    'population' => 27000000,
    'gdp' => 1880000000000,
    'latitude' => -35.2809,
    'longitude' => 149.1300,
    'risk_level' => 'Low',
    'risk_score' => 12,
    'trade_index' => 95,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'New Zealand',
    'code' => 'NZ',
    'iso3' => 'NZL',
    'capital' => 'Wellington',
    'region' => 'Oceania',
    'sub_region' => 'Australia and New Zealand',
    'currency' => 'NZD',
    'population' => 5300000,
    'gdp' => 260000000000,
    'latitude' => -41.2866,
    'longitude' => 174.7762,
    'risk_level' => 'Low',
    'risk_score' => 10,
    'trade_index' => 93,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Papua New Guinea',
    'code' => 'PG',
    'iso3' => 'PNG',
    'capital' => 'Port Moresby',
    'region' => 'Oceania',
    'sub_region' => 'Melanesia',
    'currency' => 'PGK',
    'population' => 11000000,
    'gdp' => 32000000000,
    'latitude' => -9.4438,
    'longitude' => 147.1803,
    'risk_level' => 'Medium',
    'risk_score' => 48,
    'trade_index' => 54,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Fiji',
    'code' => 'FJ',
    'iso3' => 'FJI',
    'capital' => 'Suva',
    'region' => 'Oceania',
    'sub_region' => 'Melanesia',
    'currency' => 'FJD',
    'population' => 940000,
    'gdp' => 6200000000,
    'latitude' => -18.1248,
    'longitude' => 178.4501,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 67,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Solomon Islands',
    'code' => 'SB',
    'iso3' => 'SLB',
    'capital' => 'Honiara',
    'region' => 'Oceania',
    'sub_region' => 'Melanesia',
    'currency' => 'SBD',
    'population' => 830000,
    'gdp' => 1800000000,
    'latitude' => -9.4456,
    'longitude' => 159.9729,
    'risk_level' => 'Low',
    'risk_score' => 30,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
[
    'name' => 'Vanuatu',
    'code' => 'VU',
    'iso3' => 'VUT',
    'capital' => 'Port Vila',
    'region' => 'Oceania',
    'sub_region' => 'Melanesia',
    'currency' => 'VUV',
    'population' => 340000,
    'gdp' => 1100000000,
    'latitude' => -17.7333,
    'longitude' => 168.3273,
    'risk_level' => 'Low',
    'risk_score' => 31,
    'trade_index' => 53,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Samoa',
    'code' => 'WS',
    'iso3' => 'WSM',
    'capital' => 'Apia',
    'region' => 'Oceania',
    'sub_region' => 'Polynesia',
    'currency' => 'WST',
    'population' => 225000,
    'gdp' => 1000000000,
    'latitude' => -13.8500,
    'longitude' => -171.7500,
    'risk_level' => 'Low',
    'risk_score' => 24,
    'trade_index' => 56,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Tonga',
    'code' => 'TO',
    'iso3' => 'TON',
    'capital' => 'Nukuʻalofa',
    'region' => 'Oceania',
    'sub_region' => 'Polynesia',
    'currency' => 'TOP',
    'population' => 105000,
    'gdp' => 550000000,
    'latitude' => -21.1394,
    'longitude' => -175.2049,
    'risk_level' => 'Low',
    'risk_score' => 23,
    'trade_index' => 55,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Kiribati',
    'code' => 'KI',
    'iso3' => 'KIR',
    'capital' => 'South Tarawa',
    'region' => 'Oceania',
    'sub_region' => 'Micronesia',
    'currency' => 'AUD',
    'population' => 136000,
    'gdp' => 320000000,
    'latitude' => 1.4518,
    'longitude' => 173.0326,
    'risk_level' => 'Low',
    'risk_score' => 26,
    'trade_index' => 49,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],

[
    'name' => 'Tuvalu',
    'code' => 'TV',
    'iso3' => 'TUV',
    'capital' => 'Funafuti',
    'region' => 'Oceania',
    'sub_region' => 'Polynesia',
    'currency' => 'AUD',
    'population' => 11000,
    'gdp' => 70000000,
    'latitude' => -8.5211,
    'longitude' => 179.1981,
    'risk_level' => 'Low',
    'risk_score' => 22,
    'trade_index' => 48,
    'supply_status' => 'Normal',
    'shipping_status' => 'Open',
],
        ];

        foreach ($countries as $country) {

            Country::updateOrCreate(

                ['code'=>$country['code']],

                $country

            );

        }
    }
}